# Generated by Django 4.2.1 on 2023-05-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('ano', models.PositiveSmallIntegerField()),
                ('km', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('foto', models.CharField(max_length=1000)),
            ],
        ),
    ]
