# Generated by Django 4.2.1 on 2023-05-25 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='nome',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
